<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>Debug;Release;SignedRelease</Configurations>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSource>true</IncludeSource>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'SignedRelease|AnyCPU'">
    <OutputPath>bin\SignedRelease\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <NoStdLib>true</NoStdLib>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="publish\**" />
    <EmbeddedResource Remove="publish\**" />
    <None Remove="publish\**" />
    <Page Remove="publish\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\nikoncswrapper\nikoncswrapper.csproj" />
    <ProjectReference Include="..\NINA.Astrometry\NINA.Astrometry.csproj" />
    <ProjectReference Include="..\NINA.Core\NINA.Core.csproj" />
    <ProjectReference Include="..\NINA.Image\NINA.Image.csproj" />
    <ProjectReference Include="..\NINA.MGEN\NINA.MGEN.csproj" />
    <ProjectReference Include="..\NINA.Profile\NINA.Profile.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\NINA\Resources\ninasplash.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ASCOM.Alpaca.Components" Version="3.1.0" />
    <PackageReference Include="ASCOM.Alpaca.Device" Version="3.1.0" />
    <PackageReference Include="ASCOM.Com.Components" Version="3.1.0" />
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Castle.Core.AsyncInterceptor" Version="2.1.0" />
    <PackageReference Include="Google.Protobuf.Tools" Version="3.35.1" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="GrpcDotNetNamedPipes" Version="3.1.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NJsonSchema" Version="11.6.1" />
    <PackageReference Include="SharpGIS.NmeaParser" Version="2.2.2" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="SDK\CameraSDKs\ToupTekAlike\SVBonySDK\" />
  </ItemGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>$(AssemblyName)</Title>
    <Version>3.3.0.1061-nightly</Version>
    <Authors>Stefan Berg and the N.I.N.A. Contributors</Authors>
    <Product>N.I.N.A. - Nighttime Imaging 'N' Astronomy</Product>
    <Description>This assembly contains the Equipment components of N.I.N.A. to interact and connect to various types of astronomy equipment.</Description>
    <Copyright>Copyright ©  2016 - 2026 Stefan Berg and the N.I.N.A. contributors</Copyright>
    <PackageIcon>ninasplash.png</PackageIcon>
    <PackageProjectUrl>https://nighttime-imaging.eu/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/isbeorn/nina.git</RepositoryUrl>
    <PackageOutputPath>$(SolutionDir)publish</PackageOutputPath>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec IgnoreExitCode="true" Command="   if $(Configuration) == SignedRelease signtool sign /t http://timestamp.sectigo.com /i Sectigo /v /a /fd SHA256 $(TargetPath)" />
  </Target>
</Project>