pipelines:
  custom:   
    unittests:
        - step:
            name: dotnet unit tests
            clone:
                lfs: true
            image: microsoft/dotnet:sdk
            caches:
              - dotnetcore
            script:              
              # Clone extenral folder LFS files
              - git submodule update --init --recursive
              # Build and run test project
              - dotnet test ./NINA.Test/NINA.Test.csproj -c Debug
