pipelines:
  custom:   
    unittests:
        - step:
            name: dotnet unit tests
            clone:
                lfs: true
            image: mcr.microsoft.com/dotnet/sdk:7.0
            caches:
              - dotnetcore
            script:              
              - ls
              - ls ./NINA
              - ls ./NINA/External
              - ls ./NINA/External/x64
              - ls ./NINA/External/x64/AllPro
              - git submodule update --init --recursive
              - ls
              - ls ./NINA
              - ls ./NINA/External
              - ls ./NINA/External/x64
              - ls ./NINA/External/x64/AllPro
              - dotnet test ./NINA.Test/NINA.Test.csproj -c Debug
