pipelines:
  custom:   
    unittests:
        - step:
            name: dotnet unit tests
            clone:
                lfs: true
            image: mcr.microsoft.com/dotnet/sdk:7.0
            caches:
              - dotnetcore
            script:              
              - ls
              - dotnet test ./NINA.Test/NINA.Test.csproj -c Debug
