<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>3.3.0.1059-nightly</Version>
    <Authors>Stefan Berg and the N.I.N.A. Contributors</Authors>
    <Product>N.I.N.A. - Nighttime Imaging 'N' Astronomy</Product>
    <Description>This assembly contains the Generators for Sequencer Extensions of N.I.N.A. and the plugin definitions.</Description>
    <Copyright>Copyright ©  2016 - 2026 Stefan Berg and the N.I.N.A. contributors</Copyright>
    <PackageProjectUrl>https://nighttime-imaging.eu/</PackageProjectUrl>
    <PackageIcon>ninasplash.png</PackageIcon>
    <RepositoryUrl>https://github.com/isbeorn/nina.git</RepositoryUrl>
    <PackageOutputPath>$(SolutionDir)publish</PackageOutputPath>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSource>true</IncludeSource>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup>
    <!-- Package the generator in the analyzer directory of the nuget package -->
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\NINA\Resources\ninasplash.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.6.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>