//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarDataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class cataloguenr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cataloguenr()
        {
            this.cataloguenrdsodetail = new HashSet<cataloguenrdsodetail>();
        }
    
        public long id { get; set; }
        public Nullable<long> catalogueid { get; set; }
        public Nullable<long> nr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cataloguenrdsodetail> cataloguenrdsodetail { get; set; }
    }
}
