//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarDataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogue
    {
        public string key { get; set; }
        public string name { get; set; }
    }
}
