//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarDataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class cataloguenrdsodetail
    {
        public long id { get; set; }
        public Nullable<long> cataloguenrid { get; set; }
        public Nullable<long> dsodetailid { get; set; }
    
        public virtual cataloguenr cataloguenr { get; set; }
        public virtual dsodetail dsodetail { get; set; }
    }
}
