//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarDataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsodetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dsodetail()
        {
            this.cataloguenrdsodetail = new HashSet<cataloguenrdsodetail>();
        }
    
        public long id { get; set; }
        public Nullable<double> ra { get; set; }
        public Nullable<double> dec { get; set; }
        public Nullable<double> magnitude { get; set; }
        public Nullable<double> surfacebrightness { get; set; }
        public Nullable<double> sizemin { get; set; }
        public Nullable<double> sizemax { get; set; }
        public Nullable<double> positionangle { get; set; }
        public Nullable<long> nrofstars { get; set; }
        public Nullable<double> brighteststar { get; set; }
        public string notes { get; set; }
        public string constellationkey { get; set; }
        public string dsotypekey { get; set; }
        public string dsoclasskey { get; set; }
        public string visualdescriptionkey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cataloguenrdsodetail> cataloguenrdsodetail { get; set; }
        public virtual constellation constellation { get; set; }
        public virtual dsoclass dsoclass { get; set; }
        public virtual visualdescription visualdescription { get; set; }
        public virtual dsotype dsotype { get; set; }
    }
}
