//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarDataImport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ninaEntities1 : DbContext
    {
        public ninaEntities1()
            : base("name=ninaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catalogue> catalogue { get; set; }
        public virtual DbSet<cataloguenr> cataloguenr { get; set; }
        public virtual DbSet<cataloguenrdsodetail> cataloguenrdsodetail { get; set; }
        public virtual DbSet<constellation> constellation { get; set; }
        public virtual DbSet<dsoclass> dsoclass { get; set; }
        public virtual DbSet<dsodetail> dsodetail { get; set; }
        public virtual DbSet<dsotype> dsotype { get; set; }
        public virtual DbSet<visualdescription> visualdescription { get; set; }
    }
}
